# Generated by Django 2.0.5 on 2018-06-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientbed',
            options={'verbose_name_plural': '病床(yiyuan_beds)'},
        ),
        migrations.AlterField(
            model_name='dm_ronghua',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', '女性'), ('M', '男性')], max_length=64, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', '女性'), ('M', '男性')], max_length=64, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='patientbed',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='patientbed',
            name='device_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='设备号'),
        ),
    ]
